### ISSUE TITLE
Repository license?

### ISSUE THREAD

**Issue by hofmannsven** [MrLukeSmith/zizim-oop#1]
Hi Luke,
I just stumbled upon this repository while looking for a simple URL shortener and this one really looks great. However I couldn't find any hint on the licensing of the repository. 
Is this really publicly available (open source)? Am I free to fork it to make my own version?
As far as I understand, the [GitHub licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) would allow forking but I really would feel better to have your approval.
Regards, Sven

**Comment by MrLukeSmith** [comment]
Hi Sven,
Sorry for the late reply. I didn't get a notification. If you haven't already, feel free to fork it. I should remember to add the license to the repository. It is open source. 
Cheers,
Luke.
